# Generated by Django 2.1 on 2018-09-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('age', models.DateField(verbose_name='Age')),
                ('position', models.IntegerField(choices=[(1, 'Junior'), (2, 'Middle'), (3, 'Senior'), (0, 'Fired')], default=1, verbose_name='Position')),
                ('balance', models.PositiveIntegerField(default=0, verbose_name='Balance')),
            ],
        ),
    ]
