# Generated by Django 2.1 on 2018-09-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='age',
            new_name='birthday',
        ),
    ]
