# Generated by Django 2.1 on 2018-09-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_change_birthday_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birthday',
            field=models.DateField(verbose_name='Birthday (YYYY-MM-DD)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.IntegerField(choices=[(0, 'Junior (Salary 2000)'), (1, 'Middle (Salary 3000)'), (2, 'Senior (Salary 4000)')], default=0, verbose_name='Position'),
        ),
    ]
